In [1]:
import numpy as np

**1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:**

а) 𝐴 — матрица 4×2 , 𝐵 — матрица 4×2 ;

In [20]:
A = np.array([[1,2], [5,6], [9,10], [13,14]])
B = np.array([[3,4], [7,8], [11,12], [15,16]])
A.shape, B.shape

##n/a because the number of elements in a row != the number of rows

((4, 2), (4, 2))

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3

In [23]:
A = np.array([[1,2,3,4,5], [5,6,7,8,9]])        
B = np.array([[1,2,3], [5,6,7], [9,10,11], [13,14,15], [4,8,12]])
A.shape, B.shape

((2, 5), (5, 3))

In [22]:
##B.dot(A) - n/a because the number of elements in a row (3) != the number of rows (2)
A.dot(B) ## dimension 2 × 3

array([[110, 140, 170],
       [238, 300, 362]])

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8

In [27]:
A = np.array([[1,2,3], [5,6,7], [9,10,11], [13,14,15], [4,8,12], [9,10,11], [13,14,15], [4,8,12]])
B = np.array([[1,2,3,4,5,10,3,12], [6,34,23,5,6,7,8,9], [6,34,4,5,6,11,8,9]])        
A.shape, B.shape

((8, 3), (3, 8))

In [28]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [25]:
A.dot(B) ## dimension 8 × 8

array([[  31,  172,   61,   29,   35,   57,   43,   57],
       [  83,  452,  181,   85,  103,  169,  119,  177],
       [ 135,  732,  301,  141,  171,  281,  195,  297],
       [ 187, 1012,  421,  197,  239,  393,  271,  417],
       [ 124,  688,  244,  116,  140,  228,  172,  228],
       [ 135,  732,  301,  141,  171,  281,  195,  297],
       [ 187, 1012,  421,  197,  239,  393,  271,  417],
       [ 124,  688,  244,  116,  140,  228,  172,  228]])

In [26]:
B.dot(A) ## dimension 3 × 3

array([[287, 378, 469],
       [675, 818, 961],
       [540, 668, 796]])

г) 𝐴 — квадратная матрица 4×4 , 𝐵 — квадратная матрица 4×4 .

In [35]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
B = np.array([[1,9,3,7], [5,4,7,0], [9,3,11,12], [8,14,7,2]])
A.shape, B.shape

((4, 4), (4, 4))

In [33]:
A.dot(B) ## dimension 4 × 4

array([[ 70,  82,  78, 107],
       [162, 202, 190, 247],
       [254, 322, 302, 387],
       [346, 442, 414, 527]])

In [34]:
B.dot(A) ## dimension 4 × 4

array([[164, 184, 204, 224],
       [ 88, 104, 120, 136],
       [279, 314, 349, 384],
       [349, 394, 439, 484]])

**2. Найти сумму и произведение матриц  𝐴  и  𝐵.**

In [67]:
𝐴 = np.array([[1, -2], [3, 0]])
𝐵 = np.array([[4, -1], [0, 5]])
print(f'{A} \n\n {B}')

[[ 1 -2]
 [ 3  0]] 

 [[ 4 -1]
 [ 0  5]]


**Сумма**

In [74]:
list_A = []
for lines_A in A:
    for line_A in lines_A:
        list_A.append(line_A)
    
print(list_A)

[1, -2, 3, 0]


In [75]:
list_B = []
for lines_B in B:
    for line_B in lines_B:
        list_B.append(line_B)
print(list_B)

[4, -1, 0, 5]


In [80]:
summ = [x + y for x, y in zip(list_A, list_B)]

In [85]:
np.array(summ).reshape(2,2)

array([[ 5, -3],
       [ 3,  5]])

**Произведение**

In [114]:
a = A[0][0] * B[0][0] + A[0][1] * B[1][0] 
b = A[0][0] * B[0][1] + A[0][1] * B[1][1] 
c = A[1][0] * B[0][0] + A[1][1] * B[1][0] 
d = A[1][0] * B[0][1] + A[1][1] * B[1][1] 

In [115]:
np.array([[a, b],[c, d]])

array([[  4, -11],
       [ 12,  -3]])

In [116]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

In [121]:
a = B[0][0] * A[0][0] + B[0][1] * A[1][0] 
b = B[0][0] * A[0][1] + B[0][1] * A[1][1] 
c = B[1][0] * A[0][0] + B[1][1] * A[1][0] 
d = B[1][0] * A[0][1] + B[1][1] * A[1][1] 

In [122]:
np.array([[a, b],[c, d]])

array([[ 15, -30],
       [ -1,  20]])

In [123]:
B.dot(A)

array([[ 15, -30],
       [ -1,  20]])

**3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию 3𝐴−2𝐵+4𝐶  для матриц A, B, C**

In [117]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [119]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

**4. Дана матрица  𝐴. Вычислить  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .**

In [126]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [125]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [133]:
a = A[0][0] * A.T[0][0] + A[0][1] * A.T[1][0]
b = A[0][0] * A.T[0][1] + A[0][1] * A.T[1][1]
c = A[0][0] * A.T[0][2] + A[0][1] * A.T[1][2]
d = A[1][0] * A.T[0][0] + A[1][1] * A.T[1][0]
e = A[1][0] * A.T[0][1] + A[1][1] * A.T[1][1]
f = A[1][0] * A.T[0][2] + A[1][1] * A.T[1][2]
g = A[2][0] * A.T[0][0] + A[2][1] * A.T[1][0]
h = A[2][0] * A.T[0][1] + A[2][1] * A.T[1][1]
i = A[2][0] * A.T[0][2] + A[2][1] * A.T[1][2]

In [134]:
print(np.array([[a,b,c], [d,e,f], [g,h,i]]))  #manually

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [131]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [132]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

**5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**

In [151]:
def multiply_matrices(A, B):
    result = np.array([[0,0,0],[0,0,0],[0,0,0]])  ##if error add dimensions 
    for i in range(len(A)): 

        # iterating by colomns by B  
        for j in range(len(B[0])): 

            # iterating by rows of B 
            for k in range(len(B)): 
                result[i][j] += A[i][k] * B[k][j] 

    for r in result: 
        print(r) 

In [158]:
multiply_matrices(A, A.T)

[17 18 11]
[18 29  4]
[11  4 13]


**5. Вычислить определитель:**

In [172]:
x = 1
A = np.array([[np.sin(x), np.cos(x)],[-np.cos(x), np.sin(x)]])   ## 1t task

In [174]:
det_manual = A[0][0] * A[1][1] - A[0][1] * A[1][0]
det_manual

1.0

In [175]:
det_auto = np.linalg.det(A)
det_auto

1.0

In [176]:
B = np.array([[4, 2, 3],[0, 5, 1],[0, 0, 9]])     ## 2d task

In [177]:
det_manual = 4*5*9    #for triangle matrix
det_manual

180

In [203]:
det_auto = np.linalg.det(B)
det_auto

180.0

In [179]:
C = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])     ## 3d task

In [183]:
det_manual = 1*(5*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 5*7)    
det_manual

0

In [194]:
det_auto = f'{np.linalg.det(C):.15f}'     
det_auto

'-0.000000000000001'

**6. Определитель матрицы  𝐴  равен  4 . Найти:**

а)  𝑑𝑒𝑡(𝐴^2)

In [197]:
A = 4
A**2      ##determinant

16

б)  𝑑𝑒𝑡(𝐴𝑇)

In [199]:
## determinant of A.T = determinant of A = 4

в)  𝑑𝑒𝑡(2𝐴)

In [204]:
##n/a because we don't know the amount of rows i this matrix.
##In generall we have to multiply the determinant on 2 * the number of rows.

**7. Доказать, что матрица вырожденная.**

In [205]:
D = np.array([[-2, 7, -3],[4, -14, 6],[-3, 7, 13]]) 

In [207]:
-2*D[0] == D[1]   ## linear dependence therefore determinant = 0 

array([ True,  True,  True])

As determinant = 0 we can assume that this is a degenarate matrix.

**8. Найти ранг матрицы:**

In [217]:
A = np.array([[1, 2, 3],[1, 1, 1],[2, 3, 4]])  ## 1t task

In [219]:
A[0] == A[2] - A[1]   ## rank = 2

array([ True,  True,  True])

In [214]:
r = np.linalg.matrix_rank(A)
r

2

In [216]:
B = np.array([[0, 0, 2, 1],[0, 0, 2, 2],[0, 0, 4, 3], [2, 3, 5, 6]])  ## 2d task

In [222]:
B[2] == B[0] + B[1]  ## rank = 3

array([ True,  True,  True,  True])

In [223]:
r = np.linalg.matrix_rank(B)
r

3