In [61]:
import numpy as np
import scipy
import scipy.linalg

**1. Решить систему уравнений методом Гаусса:**

𝑥1+𝑥2−𝑥3−2𝑥4 = 0

2𝑥1+𝑥2−𝑥3+𝑥4 = −2

𝑥1+𝑥2−3𝑥3+𝑥4 = 4

 |1 1 -1 -2 | 0 |          

 |2 1 -1  1 | -2|          
 
 |1 1 -3  1 | 4 |      

|1 1 -1 -2 | 0 |

|0 -1 1  5 | -2| 

|0 0 -2  3 | 4 |  

#1.ранг (обычной) = 3
#1.ранг (расширенной) = 3

**Ответ: ранг (обычной) = ранг (расширенной) | => бесконечное кол-во решений**

**2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:**

**Задание 1**

In [9]:
A_ext = np.array([[3,-1, 1, 4],[2, -5, -3, -17],[1, 1, -1, 0]])
A = np.array([[3,-1, 1],[2, -5, -3],[1, 1, -1]])
rank = np.linalg.matrix_rank(A)
rank_ext = np.linalg.matrix_rank(A_ext)

In [14]:
print(f'Task 1: rank = {rank}, rank_extended: {rank_ext}')

rank == rank_ext  #система определена, т. е. имеет единственное решение 

Task 1: rank = 3, rank_extended: 3


True

**Задание 2**

In [16]:
A_ext = np.array([[2, -4, 6, 1],[1, -2, 3, -2],[3, -6, 9, 5]])
A = np.array([[2, -4, 6],[1, -2, 3],[3, -6, 9]])
rank = np.linalg.matrix_rank(A)
rank_ext = np.linalg.matrix_rank(A_ext)

In [18]:
print(f'Task 2: rank = {rank}, rank_extended: {rank_ext}')

rank != rank_ext  #система несовместна

Task 2: rank = 1, rank_extended: 2


True

**Задание 3**

In [19]:
A_ext = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
A = np.array([[1, 2, 5], [3, 1, -8]])
rank = np.linalg.matrix_rank(A)
rank_ext = np.linalg.matrix_rank(A_ext)

In [22]:
print(f'Task 3: rank = {rank}, rank_extended: {rank_ext}')

rank == rank_ext   #система имеет бесконечное количество решений, потому что ранг меньше кол-ва неизвестных

Task 3: rank = 2, rank_extended: 2


True

**3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей**

In [28]:
A_ext = np.array([[1, 3, -2, 4, 3],[0, 5, 0, 1, 2],[0, 0, 3, 0, 4],[0, 0, 0, 2,1]])
A_ext

array([[ 1,  3, -2,  4,  3],
       [ 0,  5,  0,  1,  2],
       [ 0,  0,  3,  0,  4],
       [ 0,  0,  0,  2,  1]])

In [29]:
rank_ext = 4   #1*5*3*2=30 != 0
rank = 4
n = 4 

Ответ: система определена, т. е. имеет единственное решение, т.к rank_ext = rank = n (кол-во неизвестных)

**4. Дана система линейных уравнений, заданная расширенной матрицей**

 |1 2 3| a |          

 |4 5 6| b |          
 
 |7 8 9| c |    

**Найти соотношение между параметрами  𝑎 ,  𝑏  и  𝑐 , при которых система является несовместной.**

|1 2 3| a |

|4 5 6| b |

|7 8 9| c |

|1  2  3| a |

|0 -3 -6| b - 4a |

|0  0  0| a + c - 2b |

**Ответ:** система является несовместной при a + c - 2b = 0

**5. Решить систему уравнений методом Крамера:**

𝑥1−2𝑥2=1

3𝑥1−4𝑥2=7

In [30]:
A = np.array([[1, -2], [3, -4]])

In [32]:
det_A = 1*(-4) - (-2)*3 #определитель
det_A                   #система совместна

2

In [34]:
A_1 = np.array([[1, -2], [7, -4]])
det_A_1 = 1*(-4) - (-2)*7
det_A_1 

10

In [35]:
A_2 = np.array([[1, 1], [3, 7]])
det_A_2 = 1*7 - 1*3
det_A_2 

4

In [40]:
x1 = det_A_1 / det_A
x2 =det_A_2 / det_A
print(f'x1 = {x1}, x2 = {x2}')

x1 = 5.0, x2 = 2.0


2𝑥1−𝑥2+5𝑥3=10

𝑥1+𝑥2−3𝑥3=−2

2𝑥1+4𝑥2+𝑥3=1

In [42]:
B = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])

In [43]:
det_B = np.linalg.det(B)  #определитель
det_B                     #система совместна

42.99999999999998

In [45]:
B_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
det_B_1 = np.linalg.det(B_1)  
det_B_1

86.00000000000004

In [46]:
B_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
det_B_2 = np.linalg.det(B_2)  
det_B_2

-43.000000000000014

In [47]:
B_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
det_B_3 = np.linalg.det(B_3)  
det_B_3

42.99999999999998

In [53]:
x1 = det_B_1 / det_B
x2 =det_B_2 / det_B
x3 =det_B_3 / det_B
print(f'x1 = {x1:.0f}, x2 = {x2:.0f} x2 = {x3:.0f}')

x1 = 2, x2 = -1 x2 = 1


**6. Найти  𝐿 -матрицу  𝐿𝑈 -разложения для матрицы коэффициентов:**

In [67]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
A

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [68]:
P, L, U = scipy.linalg.lu(A)
print(L)

[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


In [65]:
B = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
B

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

In [66]:
P, L, U = scipy.linalg.lu(B)
print(L)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]


**7. Решить систему линейных уравнений методом  𝐿𝑈 -разложения**

2𝑥1+𝑥2+3𝑥3=1

11𝑥1+7𝑥2+5𝑥3=−6

9𝑥1+8𝑥2+4𝑥3=−5

In [69]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
A

array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])

|2  1 3|

|11 7 5|

|9  8 4|

In [71]:
P, L, U = scipy.linalg.lu(A)
print(L)

[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]


In [72]:
print(U)

[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


y1 = 1
0.82*y1 + y2 = -6                #y2 = - 6.82
0.18*y1 - 0.12*y2 + y3 = -5      #y3 = 6

11*x1 + 7*x2 + 5*x3 = 1           # x1 = 0.62
2.27*x2 + (-0.09)*x3 = (- 6.82)   # x2 = -2.89
2.08*x3 = 6                       # x3 = 2.88

**Не ясно, где ошибка**