In [1]:
import numpy as np

**1. Найти с помощью NumPy SVD для матрицы**

In [4]:
A = np.array([[1,2,0], [0,0,5], [3,-4,2], [1,6,5], [0,1,0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [5]:
U, s, W = np.linalg.svd(A)

In [6]:
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype = float)
D[np.diag_indices(min(A.shape))] = s

In [11]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


In [8]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [9]:
print(f'Матрица W:\n{W}')

Матрица W:
[[ 0.07116451  0.71702467  0.69340553]
 [-0.36737824  0.66514082 -0.65009301]
 [-0.92734505 -0.20847855  0.31075368]]


**2. Для матрицы из предыдущего задания найти:**

а) евклидова норма

In [36]:
print(f'Норма Фробениуса матрицы A = {np.linalg.norm(D, ord = 1):.2f}') #auto

Норма Фробениуса матрицы A = 8.82


In [37]:
print(f'Евклидова норма матрицы A, расчитаннная вручную = {D[0][0]:.2f}')   #manually

Евклидова норма матрицы A, расчитаннная вручную = 8.82


б) норма Фробениуса

In [26]:
print(f'Норма Фробениуса матрицы A = {np.linalg.norm(D):.2f}')  #auto

Норма Фробениуса матрицы A = 11.05


In [33]:
answer = 0                                                   #manually

for row in D:
    for i in row:
        answer += i**2

        
print(f'Норма Фробениуса матрицы A, расчитаннная вручную = {np.sqrt(answer):.2f}')

Норма Фробениуса матрицы A, расчитаннная вручную = 11.05
